/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_tl_androidnativedemo_navigation51_MyJniClass */

#ifndef _Included_com_tl_androidnativedemo_navigation51_MyJniClass
#define _Included_com_tl_androidnativedemo_navigation51_MyJniClass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tl_androidnativedemo_navigation51_MyJniClass
 * Method:    sum
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_tl_androidnativedemo_navigation51_MyJniClass_sum
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     com_tl_androidnativedemo_navigation51_MyJniClass
 * Method:    append
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tl_androidnativedemo_navigation51_MyJniClass_append
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tl_androidnativedemo_navigation51_MyJniClass
 * Method:    operateEle
 * Signature: ([I)[I
 */
JNIEXPORT jintArray JNICALL Java_com_tl_androidnativedemo_navigation51_MyJniClass_operateEle
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     com_tl_androidnativedemo_navigation51_MyJniClass
 * Method:    checkPwd
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_tl_androidnativedemo_navigation51_MyJniClass_checkPwd
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_tl_androidnativedemo_navigation51_MyJniClass
 * Method:    callbackAdd
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tl_androidnativedemo_navigation51_MyJniClass_callbackAdd
  (JNIEnv *, jobject);

/*
 * Class:     com_tl_androidnativedemo_navigation51_MyJniClass
 * Method:    callbackHelloFromJava
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tl_androidnativedemo_navigation51_MyJniClass_callbackHelloFromJava
  (JNIEnv *, jobject);

/*
 * Class:     com_tl_androidnativedemo_navigation51_MyJniClass
 * Method:    callbackPrintString
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tl_androidnativedemo_navigation51_MyJniClass_callbackPrintString
  (JNIEnv *, jobject);

/*
 * Class:     com_tl_androidnativedemo_navigation51_MyJniClass
 * Method:    callbackSayHello
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_tl_androidnativedemo_navigation51_MyJniClass_callbackSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
